name: consume_transformer
version: 0.0.1
author: Oliver Sand <oliver.sand@tentaclelabs.com>
description: A Barback transformer that removes files from the output of pub build and serve.
homepage: https://github.com/Fox32/consume_transformer
dependencies:
  barback: '>=0.13.0 <0.16.0'
